---
title: "DS Final Project Proposal"
author: "Jennifer Osei, Harry Wang, Angelica Vina Albarrancin, William Anderson, Riya Bhilegaonkar"
date: "2022-11-12"
output: html_document
---

#Team registration and proposal

First, you will define your teams and propose a project. This proposal should be a half-page to a page in length and include:

#The Group Members (names and UNIs)

William Anderson - waa2119
Haoyang Wang - hw2850
Jennifer Osei - jao2195
Riya Bhilegaonkar - rsb2204
Angelica Vina Albarrancin - av2718


#The Tentative Project Title:

Investigating the leading causes of death in NYC

#The Motivation for this Project:


#The Intended Final Products:



#The Anticipated Data Sources:


Helpful NYC Health Data Resources: 

* https://opendata.cityofnewyork.us/

* https://www.health.ny.gov/statistics/

* https://www.health.ny.gov/statistics/sparcs/access/


Income data: 

* https://www.point2homes.com/US/Neighborhood/NY/New-York-City-Demographics.html

* https://www.incomebyzipcode.com/newyork

* https://www.nyc.gov/site/hpd/services-and-information/area-median-income.page


#The Planned Analyses / Visualizations / Coding Challenges:


William Anderson is focusing on analyzing income as a predictor for different diseases that are the leading cause of death in NYC by analyzing the following:

* Plot the correlation between income level and life expectancy

* Conduct statistical analysis to understand if income plays a role in the survival probability of cancer, heart disease, and other diseases

* Visualize a map of neighborhoods in NYC with certain income levels and the number of healthcare facilities within a certain radius

* Stratify the leading causes of death by income level and observe trends


Jennifer Osei is focusing on website development & analyzing race and education as a predictor for different diseases that are the leading cause of death in NYC by analyzing the following:

* Plot the correlation between race, education, etc.

* Conduct statistical analysis to understand if race or educational attainment plays a role in the survival probability of cancer, heart disease, and other diseases

* Visualize a map of neighborhoods in NYC by race and education with certain and

* Stratify the leading causes of death by race, education and observe trends using plots/ dynamic plots (to visualize over time period).

* Data permitting, also want to examine access and type of health insurance its relation to death outcomes. 



#The Planned Timeline

```{r}
timeline <- cbind( Dates = c("Mo Oct 31, 2022",  "Tu Nov 8, 2022", "Sa Nov 12, 2022", "By Th Nov 18, 2022", "Tu Nov 29, 2022 (12pm - 6pm)", "Tu Dec 6, 2022 (12pm - 6pm)" ), 
                   Actions = c("Inital Team Formed / Inital Project Ideas Discussed", "Project Team Members Finalized", "Final Proposal Github Link Submitted", "Complete Project Review With TA per Schedule", " Scheduled Team Discussion Colaboration Meeting - Story Board", "Scheduled Team Discussion Colaboration Meeting - Synthesis/Video Compilation"),
                   Contributor = c("All/Team","All/Team", "JO", "All/Team", "All/Team", "All/Team"))

knitr::kable(timeline) 
```


